-- 25 posts for David (creator)
SET @uid := (SELECT id FROM users WHERE email = 'david@creatorzhive.com' LIMIT 1);

DELETE FROM posts WHERE user_id = @uid;

INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Summer vibes #1 — Dar trip recap', 'Quick recap from last weekend. Traffic was wild but the sunset delivered.', '#travel #tanzania #creator #1', CAST('["instagram","tiktok"]' AS JSON), 'published', NULL, '2026-04-07 08:28:31', 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Summer vibes #2 — Dar trip recap', 'Quick recap from last weekend. Traffic was wild but the sunset delivered.', '#travel #tanzania #creator #2', CAST('["youtube","facebook"]' AS JSON), 'published', NULL, '2026-04-15 08:28:31', 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Summer vibes #3 — Dar trip recap', 'Quick recap from last weekend. Traffic was wild but the sunset delivered.', '#travel #tanzania #creator #3', CAST('["instagram"]' AS JSON), 'published', NULL, '2026-04-19 08:28:31', 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Summer vibes #4 — Dar trip recap', 'Quick recap from last weekend. Traffic was wild but the sunset delivered.', '#travel #tanzania #creator #4', CAST('["tiktok","youtube"]' AS JSON), 'published', NULL, '2026-04-07 08:28:31', 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Summer vibes #5 — Dar trip recap', 'Quick recap from last weekend. Traffic was wild but the sunset delivered.', '#travel #tanzania #creator #5', CAST('["facebook","instagram","tiktok"]' AS JSON), 'published', NULL, '2026-05-02 08:28:31', 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Summer vibes #6 — Dar trip recap', 'Quick recap from last weekend. Traffic was wild but the sunset delivered.', '#travel #tanzania #creator #6', CAST('["instagram","tiktok"]' AS JSON), 'published', NULL, '2026-04-08 08:28:31', 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Summer vibes #7 — Dar trip recap', 'Quick recap from last weekend. Traffic was wild but the sunset delivered.', '#travel #tanzania #creator #7', CAST('["youtube","facebook"]' AS JSON), 'published', NULL, '2026-04-11 08:28:31', 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Summer vibes #8 — Dar trip recap', 'Quick recap from last weekend. Traffic was wild but the sunset delivered.', '#travel #tanzania #creator #8', CAST('["instagram"]' AS JSON), 'published', NULL, '2026-04-04 08:28:31', 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Summer vibes #9 — Dar trip recap', 'Quick recap from last weekend. Traffic was wild but the sunset delivered.', '#travel #tanzania #creator #9', CAST('["tiktok","youtube"]' AS JSON), 'published', NULL, '2026-04-10 08:28:31', 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Summer vibes #10 — Dar trip recap', 'Quick recap from last weekend. Traffic was wild but the sunset delivered.', '#travel #tanzania #creator #10', CAST('["facebook","instagram","tiktok"]' AS JSON), 'published', NULL, '2026-04-28 08:28:31', 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Scheduled collab teaser #11', 'Drafting hooks for the Safaricom integration reel.', '#collab #safaricom #11', CAST('["instagram","tiktok"]' AS JSON), 'scheduled', '2026-05-13 08:28:31', NULL, 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Scheduled collab teaser #12', 'Drafting hooks for the Safaricom integration reel.', '#collab #safaricom #12', CAST('["youtube","facebook"]' AS JSON), 'scheduled', '2026-05-13 08:28:31', NULL, 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Scheduled collab teaser #13', 'Drafting hooks for the Safaricom integration reel.', '#collab #safaricom #13', CAST('["instagram"]' AS JSON), 'scheduled', '2026-05-15 08:28:31', NULL, 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Scheduled collab teaser #14', 'Drafting hooks for the Safaricom integration reel.', '#collab #safaricom #14', CAST('["tiktok","youtube"]' AS JSON), 'scheduled', '2026-05-17 08:28:31', NULL, 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Scheduled collab teaser #15', 'Drafting hooks for the Safaricom integration reel.', '#collab #safaricom #15', CAST('["facebook","instagram","tiktok"]' AS JSON), 'scheduled', '2026-05-08 08:28:31', NULL, 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Draft idea #16 — skincare routine', 'Outline only — need b-roll from Wednesday.', '#skincare #routine #16', CAST('["instagram","tiktok"]' AS JSON), 'draft', NULL, NULL, 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Draft idea #17 — skincare routine', 'Outline only — need b-roll from Wednesday.', '#skincare #routine #17', CAST('["youtube","facebook"]' AS JSON), 'draft', NULL, NULL, 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Draft idea #18 — skincare routine', 'Outline only — need b-roll from Wednesday.', '#skincare #routine #18', CAST('["instagram"]' AS JSON), 'draft', NULL, NULL, 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Draft idea #19 — skincare routine', 'Outline only — need b-roll from Wednesday.', '#skincare #routine #19', CAST('["tiktok","youtube"]' AS JSON), 'draft', NULL, NULL, 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Draft idea #20 — skincare routine', 'Outline only — need b-roll from Wednesday.', '#skincare #routine #20', CAST('["facebook","instagram","tiktok"]' AS JSON), 'draft', NULL, NULL, 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Draft idea #21 — skincare routine', 'Outline only — need b-roll from Wednesday.', '#skincare #routine #21', CAST('["instagram","tiktok"]' AS JSON), 'draft', NULL, NULL, 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Draft idea #22 — skincare routine', 'Outline only — need b-roll from Wednesday.', '#skincare #routine #22', CAST('["youtube","facebook"]' AS JSON), 'draft', NULL, NULL, 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Failed publish attempt #23', 'API quota exceeded during upload.', '#oops #23', CAST('["instagram","tiktok"]' AS JSON), 'failed', NULL, NULL, 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Failed publish attempt #24', 'API quota exceeded during upload.', '#oops #24', CAST('["youtube","facebook"]' AS JSON), 'failed', NULL, NULL, 0);
INSERT INTO posts (user_id, cover_media_id, title, content, caption, platforms, status, scheduled_at, published_at, is_deleted) VALUES (@uid, NULL, 'Failed publish attempt #25', 'API quota exceeded during upload.', '#oops #25', CAST('["instagram"]' AS JSON), 'failed', NULL, NULL, 0);
