<?php
require_once dirname(__DIR__, 2) . '/backend/bootstrap-web-view.php';
$year = date('Y');
?>
<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light dark">
  <title>Terms of Service — CreatorzHive</title>
  <link rel="icon" type="image/svg+xml" href="<?= htmlspecialchars(asset_url('frontend/assets/icon.svg')) ?>?v=2">
  <link rel="apple-touch-icon" href="<?= htmlspecialchars(asset_url('frontend/assets/icon.svg')) ?>?v=2">
  <link rel="stylesheet" href="<?= htmlspecialchars(asset_url('frontend/css/main.css')) ?>">
  <link rel="stylesheet" href="<?= htmlspecialchars(asset_url('frontend/css/components.css')) ?>">
  <link rel="stylesheet" href="<?= htmlspecialchars(asset_url('frontend/css/dark-mode.css')) ?>">
  <link rel="stylesheet" href="<?= htmlspecialchars(asset_url('frontend/css/legal.css')) ?>">
</head>
<body class="legal-body">

<header class="legal-nav">
  <div class="legal-nav-inner">
    <a href="<?= htmlspecialchars(route_url('home')) ?>" class="legal-logo">
      <img class="legal-logo-mark" src="<?= htmlspecialchars(asset_url('frontend/assets/icon.svg')) ?>?v=2" alt="">
      <span class="legal-logo-text">CreatorzHive</span>
    </a>
    <a href="<?= htmlspecialchars(route_url('home')) ?>" class="legal-nav-back">&larr; Back to home</a>
  </div>
</header>

<main class="legal-page">
  <div class="legal-card">
    <span class="eyebrow">Legal</span>
    <h1>Terms of Service</h1>
    <p class="legal-updated">Last updated: July 9, 2026</p>

    <div class="legal-body">
      <h2>1. Agreement to Terms</h2>
      <p>By creating an account or using CreatorzHive ("we," "us," "our," or "the service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.</p>

      <h2>2. What CreatorzHive Is</h2>
      <p>CreatorzHive is a creator workspace for planning content, tracking growth analytics, and managing deals and invoices across the social platforms you connect. The service is currently offered free of charge — there is no billing, subscription, or payment step to sign up or use it.</p>

      <h2>3. Your Account</h2>
      <p>You can create an account with an email and password, or sign in with Google. You're responsible for keeping your login credentials confidential and for all activity that happens under your account. Notify us immediately if you suspect unauthorized access.</p>

      <h2>4. Connecting Social Platforms</h2>
      <p>CreatorzHive currently supports connecting Instagram, TikTok, and YouTube through each platform's official OAuth authorization flow (X/Twitter support is planned but not yet available). We only request the permissions needed to show your own analytics and let you plan posts — we never ask for your platform password, and we don't scrape or access data outside what you explicitly authorize. Access tokens are encrypted at rest. You can disconnect any platform at any time from Settings, which stops any further data collection from it.</p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Attempt to gain unauthorized access to CreatorzHive, other users' accounts, or connected platform accounts</li>
        <li>Scrape, data-mine, or harvest data from the service</li>
        <li>Interfere with or disrupt the normal operation of the service</li>
        <li>Use the service to plan or publish unlawful, harassing, or infringing content</li>
        <li>Reverse engineer or attempt to extract the source code of the service</li>
      </ul>

      <h2>6. Your Content</h2>
      <p>Content you create, upload, or plan through CreatorzHive (captions, media, notes) remains yours. We only use it to provide the service — for example, storing a draft until you publish it, or displaying it back to you in the planner.</p>

      <h2>7. Insights and Predictions</h2>
      <p>Growth deltas, insights, and predictions shown in CreatorzHive are calculated from statistics and trends in your own historical data — they are not generated by AI, and they are not financial, business, or investment advice. Past performance and projected trends are estimates and are not guaranteed to reflect future results.</p>

      <h2>8. Service Availability</h2>
      <p>CreatorzHive is provided on an "as is" and "as available" basis, without warranties of any kind, express or implied. We aim to keep the service reliable, but we don't guarantee uninterrupted access, and background jobs (like fetching updated analytics) may run on a delay rather than instantly.</p>

      <h2>9. Limitation of Liability</h2>
      <p>To the fullest extent permitted by law, CreatorzHive will not be liable for any indirect, incidental, or consequential damages arising from your use of, or inability to use, the service.</p>

      <h2>10. Termination</h2>
      <p>You may stop using CreatorzHive and disconnect your platforms at any time. We may suspend or terminate accounts that violate these Terms or that we reasonably believe pose a security risk to the service or other users.</p>

      <h2>11. Changes to These Terms</h2>
      <p>We may update these Terms as the service evolves. Continued use of CreatorzHive after a change means you accept the updated Terms. We'll update the "last updated" date above whenever this happens.</p>

      <h2>12. Contact</h2>
      <p>Questions about these Terms? Reach us at <a href="mailto:support@creatorzhive.com">support@creatorzhive.com</a>.</p>
    </div>
  </div>
</main>

<footer class="legal-footer">
  <div class="legal-footer-inner">
    <span>&copy; <?= htmlspecialchars($year) ?> CreatorzHive. All rights reserved.</span>
    <nav aria-label="Legal">
      <a href="<?= htmlspecialchars(route_url('privacy-policy')) ?>">Privacy Policy</a>
      <a href="<?= htmlspecialchars(route_url('terms-of-service')) ?>">Terms of Service</a>
    </nav>
  </div>
</footer>

</body>
</html>
